# Generated by Django 4.1.7 on 2023-02-27 13:58

import Admin_Field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Field', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default=1, help_text='please fill in address', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.PositiveIntegerField(default=1, validators=[Admin_Field.models.validate_phone_number]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='pin_code',
            field=models.IntegerField(default=743847),
        ),
    ]
