# Generated by Django 4.1.7 on 2023-02-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Field', '0002_user_address_user_phone_number_user_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pin_code',
            field=models.IntegerField(default=743847, max_length=6),
        ),
    ]
