# Generated by Django 4.1.7 on 2023-02-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Field', '0003_alter_user_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pin_code',
            field=models.IntegerField(default=743847),
        ),
    ]
