# Generated by Django 4.1.7 on 2023-02-27 14:29

import Admin_Field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Field', '0004_alter_user_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'The Geeks Field you entered is not unique.'}, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pin_code',
            field=models.IntegerField(default=743847, validators=[Admin_Field.models.validate_pin_code]),
        ),
    ]
