# Generated by Django 4.1.7 on 2023-02-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Field', '0005_alter_user_email_alter_user_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_text',
            field=models.TextField(blank=True, max_length=650, null=True),
        ),
    ]
