# Generated by Django 4.1.7 on 2023-02-27 13:20

import Validate_Admin.admin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Validate_Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeeksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geeks_mail', models.CharField(max_length=200, validators=[Validate_Admin.admin.validate_geeks_mail])),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
