# Generated by Django 4.1.7 on 2023-02-28 13:47

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Task_2', '0003_alter_entry_blog_alter_entry_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='author',
            managers=[
                ('author', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='blog',
            managers=[
                ('blog', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='entry',
            managers=[
                ('entry', django.db.models.manager.Manager()),
            ],
        ),
    ]
