# Generated by Django 4.1.7 on 2023-02-28 13:51

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Task_2', '0004_alter_author_managers_alter_blog_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='author',
            managers=[
                ('author_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='blog',
            managers=[
                ('blog_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='entry',
            managers=[
                ('entry_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
